-- ===========================================================================
-- R__sp_process_order.sql
--
-- Procedimiento que el backend invoca al confirmar una compra. Registra la orden
-- con su descuento aplicado y el evento web que la originó, en una sola unidad.
-- ===========================================================================

-- ¿Por qué este archivo se ejecuta DESPUÉS de R__fn_calculate_discount, si Flyway
-- no sabe que uno depende del otro? Porque los repeatables se aplican en orden
-- alfabético por descripción, y "fn_calculate_discount" < "sp_process_order".
-- Es una dependencia que funciona por suerte tipográfica, y eso es frágil: si
-- mañana renombras la función a "z_descuento", este script fallaría.
-- Cuando el orden importa de verdad, se fuerza con el prefijo de orden de Flyway:
-- R__ acepta un número tras la doble barra baja en la configuración
-- (`flyway.repeatableSqlMigrationPrefix`), o se nombran los archivos con un
-- prefijo numérico propio: R__01_fn..., R__02_sp...

CREATE OR REPLACE PROCEDURE sp_process_order(
    p_account_id   INTEGER,
    p_standard_qty INTEGER,
    p_gloss_qty    INTEGER,
    p_poster_qty   INTEGER,
    p_channel      TEXT,
    p_utm_source   TEXT DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
DECLARE
    -- Precios de lista de Parch & Posey, derivados de los datos históricos.
    c_precio_standard CONSTANT NUMERIC(6,2) := 4.99;
    c_precio_gloss    CONSTANT NUMERIC(6,2) := 7.49;
    c_precio_poster   CONSTANT NUMERIC(6,2) := 8.12;

    v_bruto     NUMERIC(12,2);
    v_tasa      NUMERIC(4,3);
    v_std_usd   NUMERIC(10,2);
    v_gls_usd   NUMERIC(10,2);
    v_pst_usd   NUMERIC(10,2);
    v_order_id  INTEGER;
    v_event_id  INTEGER;
BEGIN
    -- Validar antes de escribir. Sin esto, la foreign key también rechazaría la
    -- inserción, pero con un mensaje del motor que no le dice nada al que llamó.
    IF NOT EXISTS (SELECT 1 FROM accounts WHERE id = p_account_id) THEN
        RAISE EXCEPTION 'La cuenta % no existe', p_account_id
            USING HINT = 'Verifica el account_id contra la tabla accounts.';
    END IF;

    IF COALESCE(p_standard_qty, 0) + COALESCE(p_gloss_qty, 0) + COALESCE(p_poster_qty, 0) <= 0 THEN
        RAISE EXCEPTION 'Una orden debe tener al menos una unidad de algún producto.';
    END IF;

    v_bruto := COALESCE(p_standard_qty, 0) * c_precio_standard
             + COALESCE(p_gloss_qty,    0) * c_precio_gloss
             + COALESCE(p_poster_qty,   0) * c_precio_poster;

    -- Aquí es donde el procedimiento se apoya en la función: el SP orquesta, la
    -- función decide. Separarlos permite cambiar la política comercial de
    -- descuentos sin volver a tocar la lógica de inserción.
    v_tasa := fn_calculate_discount(v_bruto);

    -- El descuento se aplica línea por línea, no solo al total. Si lo aplicáramos
    -- únicamente a total_amt_usd, la suma de las tres líneas dejaría de cuadrar con
    -- el total y cualquier reporte que agregue por producto daría cifras distintas
    -- a uno que agregue por orden. Datos que se contradicen entre sí son peores
    -- que datos ausentes: nadie sabe cuál creer.
    v_std_usd := ROUND(COALESCE(p_standard_qty, 0) * c_precio_standard * (1 - v_tasa), 2);
    v_gls_usd := ROUND(COALESCE(p_gloss_qty,    0) * c_precio_gloss    * (1 - v_tasa), 2);
    v_pst_usd := ROUND(COALESCE(p_poster_qty,   0) * c_precio_poster   * (1 - v_tasa), 2);

    -- ¿Por qué calculamos el id con MAX(id)+1 en lugar de dejar que la base lo
    -- genere? Porque las tablas se cargaron en la Sesión 1 con ids explícitos del
    -- dataset original, sin secuencia asociada. Esto NO es apto para producción:
    -- dos transacciones concurrentes leerían el mismo MAX y una fallaría por clave
    -- duplicada. La solución correcta es una migración V__ que convierta la columna
    -- en GENERATED BY DEFAULT AS IDENTITY y ajuste la secuencia al máximo actual.
    -- Queda como ejercicio propuesto — y como recordatorio de que una deuda técnica
    -- documentada es manejable, y una silenciosa no.
    SELECT COALESCE(MAX(id), 0) + 1 INTO v_order_id FROM orders;

    INSERT INTO orders (
        id, account_id, occurred_at,
        standard_qty, gloss_qty, poster_qty, total,
        standard_amt_usd, gloss_amt_usd, poster_amt_usd, total_amt_usd
    ) VALUES (
        v_order_id, p_account_id, now(),
        COALESCE(p_standard_qty, 0), COALESCE(p_gloss_qty, 0), COALESCE(p_poster_qty, 0),
        COALESCE(p_standard_qty, 0) + COALESCE(p_gloss_qty, 0) + COALESCE(p_poster_qty, 0),
        v_std_usd, v_gls_usd, v_pst_usd, v_std_usd + v_gls_usd + v_pst_usd
    );

    -- El evento web que originó la compra, con su atribución de campaña.
    -- Esta es la línea que el backend ejecuta cuando llega una visita desde Google
    -- Ads. Recuérdala: en el paso 4 del taller es la que va a reventar.
    SELECT COALESCE(MAX(id), 0) + 1 INTO v_event_id FROM web_events;

    INSERT INTO web_events (id, account_id, occurred_at, channel, utm_source)
    VALUES (v_event_id, p_account_id, now(), p_channel, p_utm_source);

    RAISE NOTICE 'Orden % registrada: bruto %, descuento % %%, neto %',
        v_order_id, v_bruto, v_tasa * 100, v_std_usd + v_gls_usd + v_pst_usd;
END;
$$;

-- ¿Por qué PROCEDURE y no FUNCTION? Un procedure se invoca con CALL y puede
-- manejar transacciones (COMMIT / ROLLBACK) en su interior; una función se ejecuta
-- siempre dentro de la transacción de quien la llama. Para algo que escribe en
-- varias tablas, PROCEDURE es la herramienta correcta.

COMMENT ON PROCEDURE sp_process_order(INTEGER, INTEGER, INTEGER, INTEGER, TEXT, TEXT) IS
    'Registra una orden con descuento por volumen y su evento web de origen.';
